### ISSUE TITLE
Electron Upgrade: Task Inventory

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-desktop#736]
~~**Status 1/7/2020**: The Electron upgrade is currently WIP. We have one remaining task, which is to address regressions in `electron-spellchecker` behavior.~~

~~**Status 1/21/2020**: All task items have been resolved and the Electron upgrade is feature complete. 🎉 Next steps: (1) merge pending Calypso PR (github/Automattic/wp-calypso#38986) that helps fix the spellchecker, (2) refactor and clean up upgrade work, and (3) merge to `develop`.~~

**Status 2/4/2020**: Complete! (Merged in #757)

### Task Inventory

- [x] Upgrade Electron to v4.2.9
- [x] Dependencies: `electron-builder`, `electron-updater`
- [x] Dependencies: replace `electron-spellchecker` prebuilt with source
- [x] Fix breaking API changes since v1.x: 
    * `crashReporter`
    * `makeSingleInstance`
    * `session.setProxy`
-  [x] CI: Fix e2e test breakages, update `electron-chromedriver`, update user-agent info
-  [x] CI [Enhancement]: Add e2e utility script to prep for local and cross-platform invocation
 - [x] CI [Mac]: Update Xcode image to 10.1.0
-  [x] CI [Linux]: Add `libxext-dev` and `libx11-dev` for spellchecker compilation
-  [x] CI [Windows]: Remove Windows build from Circle CI
-  [x] CI [Windows]: Enable AppVeyor for Windows build and deployment
-  [x] Fix regressions in `electron-spellchecker` behavior

Addresses #588
